link:
  railstutorial:
    home: "https://www.railstutorial.org/"
    help: "https://www.railstutorial.org/help"
    book: "https://www.railstutorial.org/book"
    news: "https://news.railstutorial.org/"
    screencasts: "https://screencasts.railstutorial.org/"
    au: "https://www.michaelhartl.com/"
  learnenough: 
    home: "https://www.learnenough.com/"
